-- SQLite
-- DM2 Hadi NAÏMI & Lohan COUDOUX
-- Question 4
/*CREATE TABLE PILOTE (
  NUMPIL INTEGER PRIMARY KEY NOT NULL,
  NOMPIL VARCHAR NOT NULL,
  PRENOMPIL VARCHAR NOT NULL, 
  ADRESSE VARCHAR NOT NULL, 
  SALAIRE DOUBLE NOT NULL, 
  PRIME DOUBLE NOT NULL
);

INSERT INTO PILOTE (
  NUMPIL, 
  NOMPIL, 
  PRENOMPIL, 
  ADRESSE, 
  SALAIRE, 
  PRIME
  ) VALUES (
  1,
  'Emmanuel',
  'MACRON',
  'Marseille',
  2000,
  0
  ), (
  2,
  'François',
  'HOLLANDE',
  'Marseille',
  2500,
  500
  ), (
  3, 
  'Nicolas',
  'SARKOZY',
  'Bordeaux',
  3000,
  1000
  ), (
  4,
  'Jacques',
  'CHIRAC',
  'Bordeaux',
  3500,
  1500
  ), (
  5,
  'François',
  'MITTERRAND',
  'Paris',
  4000,
  2000
  ), ( 
  6, 
  'Georges',
  'POMPIDOU',
  'Paris',
  4000,
  3000
); */


/* CREATE TABLE AVION (
  NUMAV INTEGER PRIMARY KEY NOT NULL,
  NOMAV VARCHAR NOT NULL,
  CAPACITE INTEGER NOT NULL, 
  LOCALISATION VARCHAR NOT NULL
);

INSERT INTO AVION (
  NUMAV, 
  NOMAV, 
  CAPACITE, 
  LOCALISATION 
  ) VALUES 
  (11,
  'A300',
  300,
  'Marseille'),
  
  (22,
  'A310',
  310,
  'Marseille'), 

  (33,
  'A320',
  320,
  'Bordeaux'),
  
  (44,
  'A330',
  330,
  'Bordeaux'), 

  (55,
  'A340',
  340,
  'Paris'), 
  
  (66,
  'A350',
  350,
  'Paris');
*/
--PRAGMA foreign_keys = ON;
/* CREATE TABLE VOL (
  NUMVOL VARCHAR PRIMARY KEY NOT NULL,
  NUMPIL INTEGER NOT NULL,
  NUMAV INTEGER NOT NULL,
  DATE_VOL DATE NOT NULL,
  HEURE_DEP TIME NOT NULL,
  HEURE_ARR TIME NOT NULL,
  VILLE_DEP VARCHAR NOT NULL, 
  VILLE_ARR VARCHAR NOT NULL, 
  FOREIGN KEY (NUMPIL) REFERENCES PILOTE (NUMPIL),
  FOREIGN KEY (NUMAV) REFERENCES AVION (NUMAV)
);

INSERT INTO VOL (
  NUMVOL,
  NUMPIL, 
  NUMAV,
  DATE_VOL,
  HEURE_DEP,
  HEURE_ARR,
  VILLE_DEP, 
  VILLE_ARR) VALUES 
  ('IT100',
  1,
  11,
  '2023-01-01',
  '08:00:00',
  '09:00:00',
  'Marseille',
  'Bordeaux'
); */

--Question 1
-- SELECT NUMPIL, NOMPIL FROM PILOTE;

--Question 2 
-- SELECT DISTINCT VILLE_DEP FROM VOL;

--Question 3
/*SELECT DISTINCT P.NOMPIL
FROM PILOTE P
WHERE P.ADRESSE LIKE 'Marseille'; */

--Question 4
-- SELECT NOMPIL, ADRESSE FROM PILOTE WHERE SALAIRE + PRIME > 3000;

--Question 5
--SELECT * FROM AVION WHERE NOMAV IN ('A310', 'A320', 'A330', 'A340');

--Question 6 
--SELECT NOMPIL FROM PILOTE WHERE SALAIRE + PRIME BETWEEN 3000 AND 5000;

--Question 7
--SELECT CAPACITE FROM AVION WHERE NOMAV LIKE 'Airbus';

--Question 8
--SELECT DISTINCT NOMAV FROM AVION WHERE NOMAV NOT IN ('A310', 'A320', 'A330', 'A340');

--Question 9
/* SELECT *
FROM VOL 
WHERE VILLE_DEP = 'Marseille' AND VILLE_ARR = 'Paris'; */ 

--Question 10
--SELECT AVG(SALAIRE + PRIME) AS revenumensuel_bordelais FROM PILOTE WHERE ADRESSE LIKE 'Bordeaux';

--Question 11
/*SELECT NOMPIL, PRENOMPIL, NUMPIL, SALAIRE + PRIME AS REVENUS_ACTUEL, (SALAIRE + PRIME + (PRIME * 0.1)) AS REVENUS_SIMULES
FROM PILOTE
WHERE (SALAIRE + PRIME + (PRIME * 0.1)) < 5000; */

--Question 12
/* SELECT AVG(SALAIRE) AS SALAIRE_MOYEN
FROM PILOTE
WHERE ADRESSE = 'Marseille'; */

--Question 13
/* SELECT COUNT(*) AS NB_VOLS_DEPART_MARSEILLE
FROM VOL
WHERE VILLE_DEP = 'Marseille'; */

--Question 14
/* SELECT COUNT(DISTINCT VILLE_ARR) AS NB_DESTINATIONS_DESSERVIES_BORDEAUX
FROM VOL
WHERE VILLE_DEP = 'Bordeaux'; */

--Question 15
/*SELECT P.NUMPIL, P.NOMPIL
FROM PILOTE P 
JOIN AVION A
WHERE A.NUMAV = 33 AND P.ADRESSE = A.LOCALISATION;*/

--Question 16
/* SELECT DISTINCT PILOTE.NOMPIL
FROM PILOTE
JOIN AVION 
JOIN VOL ON PILOTE.NUMPIL = VOL.NUMPIL AND AVION.NUMAV = VOL.NUMAV
WHERE VOL.VILLE_DEP = 'Marseille' AND AVION.NOMAV LIKE '%A%'; */

--Question 17
/*SELECT * FROM AVION 
WHERE LOCALISATION = (SELECT LOCALISATION AS LOCALISATION_103_11 FROM AVION WHERE NUMAV = 11); */

--Question 18
--SELECT DISTINCT VILLE_ARR FROM VOL WHERE VILLE_DEP = (SELECT VILLE_ARR FROM VOL WHERE NUMVOL = 'IT100');

--Question 19
/*SELECT NOMPIL, PRENOMPIL
FROM PILOTE
WHERE SALAIRE > (SELECT AVG(SALAIRE) FROM PILOTE)*/

--Question 20
/*SELECT DISTINCT NOMPIL, PRENOMPIL
FROM PILOTE
JOIN VOL ON PILOTE.NUMPIL = VOL.NUMPIL
WHERE VILLE_DEP = 'Marseille';*/

--Question 21
/* SELECT A1.NUMAV
FROM AVION AS A1, AVION AS A2, VOL V
WHERE A1.LOCALISATION='Marseille'
AND A1.CAPACITE>A2.CAPACITE
AND A2.NUMAV=V.NUMAV
AND V.VILLE_DEP IN ('Paris','Marseille')
AND V.VILLE_ARR IN ('Paris','Marseille'); */

-- Question 22
/*
SELECT DISTINCT NOMPIL, PRENOMPIL
FROM PILOTE
WHERE ADRESSE = 'Marseille'
  AND SALAIRE > (
    SELECT MAX(SALAIRE)
    FROM PILOTE
    WHERE ADRESSE = 'Paris'
  );
*/

--Question 23
/*SELECT DISTINCT PILOTE.NOMPIL, PILOTE.PRENOMPIL
FROM PILOTE
JOIN VOL ON PILOTE.NUMPIL = VOL.NUMPIL
WHERE PILOTE.ADRESSE = 'Marseille'
  AND PILOTE.SALAIRE > (
    SELECT MAX(SALAIRE)
    FROM PILOTE
    JOIN VOL ON PILOTE.NUMPIL = VOL.NUMPIL
    WHERE PILOTE.ADRESSE = 'Paris'
  )
LIMIT 1; */

--Question 24
/* SELECT NOMPIL, PRENOMPIL
FROM PILOTE
WHERE SALAIRE = (
    SELECT SALAIRE 
    FROM PILOTE
    WHERE NOMPIL = 'Macron'
    AND ADRESSE = (
        SELECT ADRESSE 
        FROM PILOTE
        WHERE NOMPIL = 'Macron'
    )
) 
AND ADRESSE = (
    SELECT ADRESSE 
    FROM PILOTE
    WHERE NOMPIL = 'Macron'
); */

--Question 25
/* SELECT NOMPIL, PRENOMPIL, SALAIRE
FROM PILOTE
WHERE ADRESSE = 'Marseille'
ORDER BY SALAIRE DESC, NOMPIL ASC;*/

--Question 26
/*SELECT NOMPIL, PRENOMPIL
FROM PILOTE
WHERE NUMPIL NOT IN (
    SELECT NUMPIL
    FROM VOL
); */

--Question 27
/* SELECT NOMPIL, PRENOMPIL, COUNT(NUMVOL) AS NB_VOLS
FROM PILOTE LEFT JOIN VOL
ON PILOTE.NUMPIL = VOL.NUMPIL
GROUP BY PILOTE.NUMPIL
ORDER BY NB_VOLS DESC; */

--Question 28
/* SELECT NOMPIL, PRENOMPIL, NOMAV, COUNT(NUMVOL) AS NB_VOLS
FROM PILOTE INNER JOIN VOL
ON PILOTE.NUMPIL = VOL.NUMPIL
INNER JOIN AVION
ON VOL.NUMAV = AVION.NUMAV
GROUP BY PILOTE.NUMPIL, AVION.NUMAV
ORDER BY NOMPIL, NOMAV; */

--Question 30
/* SELECT PILOTE.NOMPIL, PILOTE.PRENOMPIL, COUNT() AS NombreVols
FROM PILOTE
INNER JOIN VOL ON PILOTE.NUMPIL = VOL.NUMPIL
GROUP BY PILOTE.NUMPIL
HAVING COUNT() > 1; */ 

--Question 32
/*SELECT DISTINCT NUMPIL
FROM VOL
WHERE NUMAV NOT IN (
  SELECT DISTINCT NUMAV
  FROM AVION
); */

--Question 32
SELECT P.NUMPIL
FROM PILOTE P 
WHERE NOT EXISTS (SELECT * FROM AVION A
WHERE NOT EXISTS (SELECT * FROM VOL V
WHERE V.NUMPIL=P.NUMPIL
AND V.NUMAV=A.NUMAV));



























